name: cell_tracking
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python
  - numpy
  - ca-certificates
  - openssl
  - matplotlib
  - ipykernel
  - pillow
  - certifi
  - nd2reader
  - pandas
  - pycodestyle
  - snakemake
  - graphviz


