name: Unit and functional tests

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  run_unit_tests:
    defaults:
      run:
        shell: bash -el {0}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true  # Ensure Git LFS files are pulled
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          environment-name: cell_tracking
      - run: |
          git lfs install
          git lfs pull
          python test/unit/test_cell_tracking.py

  run_func_tests:
    defaults:
      run:
        shell: bash -el {0}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true  # Ensure Git LFS files are pulled
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          environment-name: cell_tracking
      - run: |
          git lfs install
          git lfs pull
          bash test/func/test_do_tracking.sh

#   run_style_tests:
#     defaults:
#       run:
#         shell: bash -el {0}
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: mamba-org/setup-micromamba@v1
#         with:
#           environment-file: environment.yml
#           environment-name: swe4s
#       - run: |
#           pycodestyle src/do_tracking.py
#           pycodestyle src/read_nd2.py
#           pycodestyle src/tracking_utils.py
#           pycodestyle src/cell.py
          
          